/**
 * index.ts — Entry point for the AgentClear buyer agent demo.
 *
 * Run:
 *   npm run demo            (via tsx, no build step)
 *   npm run build && npm start
 *
 * Required env vars — copy .env.example to .env and fill in:
 *   BUYER_PRIVATE_KEY  — EVM private key (0x-prefixed), generated by npm run wallets
 *   SELLER_URL         — seller endpoint (default: http://localhost:4022/analyze)
 *   WALLET_PASSWORD    — Blackbox wallet password (default: agentclear-demo-2026)
 *
 * Optional:
 *   SOURCE_CHAIN       — chain where buyer deposits (default: base_sepolia)
 *   TARGET_CHAIN       — chain where seller receives payment (default: base_sepolia)
 *   DKG_NODE_1…5       — Blackbox DKG node URLs (defaults to theblackbox.network)
 */

import "dotenv/config";
import { runDemo, printSummary } from "./demo.js";

async function main(): Promise<void> {
  try {
    const result = await runDemo();
    printSummary(result);
    process.exit(0);
  } catch (err: unknown) {
    console.error("\nDemo failed:");
    if (err instanceof Error) {
      console.error("  ", err.message);
      if (process.env.DEBUG) {
        console.error(err.stack);
      }
    } else {
      console.error("  ", err);
    }
    process.exit(1);
  }
}

main();
